name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
void setup() {
  // initialize the serial communication:
  Serial.begin(9600);
  pinMode(10, INPUT);
  pinMode(10, INPUT); // Setup for leads off detection LO +
  pinMode(11, INPUT); // Setup for leads off detection LO -

}

void loop() {
  // send the value of analog input 0:

  if((digitalRead(10) == 1)||(digitalRead(11) == 1)){
    Serial.println('!');
  }
  else{
    Serial.println(analogRead(A0));
    // send the value of analog input 0:
      Serial.println(analogRead(A0));
  }
  // wait a bit for the analog-to-digital converter 
  // to stabilize after the last reading:

  delay(2);
  //Wait for a bit to keep serial data from saturating
  delay(1);
}
